### ISSUE TITLE
Add JDK 10 and 11 CI builds

### ISSUE THREAD

**Issue by offa** [offa/NB-CMake-Completion#22]
Add JDK 10 / 11 CI builds (related to #21).

**Comment by wltjr** [comment]
JDK 11 was just released today and is LTS. May want to skip 10 for 11. Or will need to repeat again for 11.

**Comment by offa** [comment]
Wow, there's already a OpenJDK11 images.

Thanks for the hint @wltjr

**Comment by offa** [comment]
Both added.
