### ISSUE TITLE
All Builds fail due a broken Oracle JDK 7 on travis

### ISSUE THREAD

**Issue by offa** [offa/NB-CMake-Completion#9]
All Builds fail due a broken Oracle JDK 7 on travis. See https://github.com/offa/NBCndUnit/issues/28.

**Comment by offa** [comment]
See also #7

**Comment by ghost** [comment]
How is this closed? I'm still having this issue

**Comment by offa** [comment]
The Oracle JDK 7 is no longer supported by Oracle. So the only solution for this issue is to drop `oraclejdk7` CI builds. The (working) alternative is OpenJDK 7 (`openjdk7` on Travis).

The related Issues at Travis:

- https://github.com/travis-ci/travis-ci/issues/7019
- https://github.com/travis-ci/travis-ci/issues/7964

There are many other issues related, but these two are the main ones.
